return {
  { "nvim-neo-tree/neo-tree.nvim", enabled = false },
  { "nvimdev/dashboard-nvim", enabled = false },
  { "rcarriga/nvim-notify", enabled = false },
  { "rcarriga/nvim-notify", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "akinsho/bufferline.nvim", enabled = false },
  { "akinsho/bufferline.nvim", enabled = false },
  { "nvim-pack/nvim-spectre", enabled = false },
  { "folke/persistence.nvim", enabled = false },
  { "RRethy/vim-illuminate", enabled = false },
  { "echasnovski/mini.bufremove", enabled = false },
  { "folke/todo-comments.nvim", enabled = false },
  { "echasnovski/mini.ai", enabled = false },
  { "echasnovski/mini.animate", enabled = false },
  { "echasnovski/mini.pairs", enabled = false },
  { "stevearc/dressing.nvim", enabled = false },
  { "lukas-reineke/headlines.nvim", enabled = false },
  { "nvim-treesitter-context", enabled = false },
  { "windwp/nvim-ts-autotag", enabled = false },
}
