return {
  -- add more treesitter parsers
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "c",
        -- "c_sharp",
        -- "css",
        "csv",
        "diff",
        "dot",
        "git_config",
        "gitcommit",
        "gitignore",
        "go",
        "html",
        "htmldjango",
        "http",
        "ini",
        "javascript",
        "jsonc",
        "latex",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "query",
        "regex",
        "ruby",
        "rust",
        "scss",
        "sql",
        "svelte",
        "tsv",
        "vim",
        "vimdoc",
        "vue",
        "xml",
      },
    },
  },
}
